### ISSUE TITLE
Set to 85% of the read by default

### ISSUE THREAD

**Issue by freekvh** [nunofonseca/irap#25] opened 2017-04-21 12:25 UTC
Dear mr. Fonseca,

In irap_fastq_qc there is this part (line 266, see below) which cuts read length by 15%. I was wondering why this is? also, there does not seem to be a way to change this setting other than altering the code, am I correct?
(Shouldn't reads only be cut based on their quality, I mean some reads are showing very high phred scores after 140 bases even.)

#Minimum length of a read after filtering
#Set to 85% of the read by default
ifndef min_len
min_len=$(shell perl -e "print int($(read_size)*0.85)")
endif
bases2trim=$(shell perl -e "print $(read_size)-$(min_len)")
$(info * min_len=$(min_len))

**Comment by nunofonseca** [comment] 2017-04-21 12:59
Hi,
Cutting the reads and other QC detais is briefly  described in the iRAP manuscript (biorxiv). That is done to ensure that all reads have the same length after trimming the bases by phred score. You can disable this behavior by setting     min_len to 0.
Cheers.

**Comment by freekvh** [comment] 2017-08-21 12:54
Hi Nuno, it has been a while but we tried your suggestion of setting min_len to 0, by two methods, first I added the parameter to the conf file:

    ######################################
    # QC
    # Check data (reads) quality (on|off|none)
    # on  - reads are filtered out based on their quality
    # off - the quality of the reads is assessed but no filtering is done
    # none- no quality control is performed
    qual_filtering=on
    
    # Trim all reads to the minimum read size after quality trimming -  Yes (y)| No (n)
    # only applicable if qual_filtering is on
    trim_reads=y
    
    # Minimum base quality accepted (def. 10)
    min_read_quality=10

    # Prevent clipping of the reads by 15% <= added for swo-223 specifically
    min_len=0

Also, a colleague changed the setting in scripts/irap_fastq_qc:

    #Minimum length of a read after filtering
    #Set to 85% of the read by default <= Changed to 100%
    ifndef min_len
    #min_len=$(shell perl -e "print int($(read_size)*0.85)")
    min_len=$(shell perl -e "print int($(read_size)*1.00)")
    endif
    bases2trim=$(shell perl -e "print $(read_size)-$(min_len)")
    $(info * min_len=$(min_len))

Still, looking at the fastqc repors and analyzing the Tophat2 bam file, we see reads of 64 bp instead of 76.

Do you have any idea what could be wrong?

Highest regards,

Freek.

**Comment by nunofonseca** [comment] 2017-08-21 13:15
Hi Freek,

Your message contains the answer;-)
# Trim all reads to the minimum read size after quality trimming -  Yes (y)| No (n)
# only applicable if qual_filtering is on
trim_reads=y

To disable trimming:
trim_reads=n

Hope that this helps. 
Cheers.

**Comment by nunofonseca** [comment] 2017-08-21 13:46
ah,I forgot to include the minimum read size/length parameter in the example configuration file. I added the following description to the wiki page, please let me know if makes sense to you

Minimum read size/length after trimming
If trimming is enabled, reads will be trimmed to have the number of bases defined by this parameter.
By default, if trimming is enabled, reads will be trimmed to have 85% of the original length. 
min_read_length=50

Indeed some tools will require the reads to have the same length. If this is not the case for the tools that you are using then you may have quality filtering without trimming by setting

qual_filtering=on
trim_reads=n
min_read_quality=20  (or other phred value)

Makes sense?
Cheers.

**Comment by nunofonseca** [comment] 2017-08-30 10:37
Hi Freek,
Did it work?
Cheers.

**Comment by freekvh** [comment] 2017-09-13 11:36
Hi Nuno, thanx for the inquiry, I just got back from vacation and will resume my trials shortly...

**Comment by nunofonseca** [comment] 2017-10-18 11:51
Closing this one. Please reopen if the problem is not fixed. 
Cheers.

**Closed by nunofonseca** 2017-10-18 11:51 UTC

**Comment by freekvh** [comment] 2018-01-12 12:15
Hi Nuno,

Again, it has been a while, my apologies.

I have now run pipelines using these settings:

```
######################################
# QC
# Check data (reads) quality (on|off|none)
# on  - reads are filtered out based on their quality
# off - the quality of the reads is assessed but no filtering is done
# none- no quality control is performed
qual_filtering=on

# Trim all reads to the minimum read size after quality trimming -  Yes (y)| No (n)
# only applicable if qual_filtering is on
trim_reads=n

# Minimum base quality accepted (def. 10)
min_read_quality=10
```

But still, the fastqc report of
``/xs-0011_003_P2017SEQE25R_S1/report/riq/raw_data/xs-0011_003_P2017SEQE25R_S1Lib_2.f_fastqc.html``
and the bamfile:
```samtools view xs-0011_003_P2017SEQE25R_S1Lib.pe.hits.bam | awk '{print length($10)}' | head -10000 | sort -u
64```

report 64 bp instead of 76 bp.

I think the star mapper can handle a distribution in read lengths and it seems like a waste to throw away 15% of all reads whereas many reads are still very high quality at base 76.

Am I still missing something here?

Highest regards,

Freek.

**Comment by nunofonseca** [comment] 2018-01-15 09:13
Hi  Freek,

So, did you run iRAP, changed the above settings in the configuration file and then reran iRAP again with the modified configuration file? 

iRAP follows a lazy approach to generate files - once a file is produced (e.g., a BAM) it will only regenerate that file if the files used to generate that file (e.g., fastq+GTF+reference genome) are modified (it uses the file timestamp to determine changes) - for performance reasons iRAP ignores changes in the settings file when deciding to regenerate a file. 

This means that if you successfully run iRAP with a configuration file and then  only change the QC filtering settings, the previously filtered fastq files will not be updated. To force the regeneration of the fastq files you can:
1) delete the fastq files in $(name)/data (where name is defined in the conf. file)
or
2) update the timestamp of the original fastq files using the 'touch' command
or 
3) run iRAP with the -B option (this will force all files to be regenerated)

Cheers.

**Comment by freekvh** [comment] 2018-03-22 08:12
Hi Nuno,

It took a while but I can confirm that running iRAP with the -B option solved my problem. Probably indeed it was the lazy approach of iRAP then (and my laziness in not creating new files). Thank you for the suggestions.

But... (as seemingly always) a new issue arises. the last 2-3 bases are heavily biased, for example in the last base of a read, there is never an A. Apparently this is due to the base-calling process, which requires flanking bases for calibration. I have looked for an option like "trim_traling_bases=3" but this does not seem to exist in iRAP... or does it :) ?

**Comment by nunofonseca** [comment] 2018-03-26 10:25
Hi, 

As I mentioned you could have simply "touch" the fastq files - it would have been faster ;-)

Regarding the trim_trailing bases option...it didn't exit but now  there is a trim_n_trailing_bases parameter that does what you described (it is off/set to zero by default). It is currently only in the devel version but it will be available in the next  release of iRAP that should come out in a few days.

Cheers.
