### ISSUE TITLE
Problem with Report generation

### ISSUE THREAD

**Issue by Niklas123Niklas** [nunofonseca/irap#33] opened 2017-09-07 07:48 UTC
Hey there,

I have Problems regarding the report generation. The analysis seems to be fine, but in report, it stops with a error. You can find the log of the report and the analysis (which seems to be missing some on the beginning?!) attached.
[AnalysisLog.txt](https://github.com/nunofonseca/irap/files/1283816/AnalysisLog.txt)
[ReportLog.txt](https://github.com/nunofonseca/irap/files/1283819/ReportLog.txt)

And I often get the following warning. Is this harmfull? 

```
In fread(input = f, sep = "\t", header = "auto", check.names = FALSE,  :
  Bumped column 19 to type character on data row 124, field contains '04110;04114;04115;04914;05200;05215;05222'. Coercing previously read values in this column from logical, integer or numeric back to character which may not be lossless; e.g., if '00' and '000' occurred before they will now be just '0', and there may be inconsistencies with treatment of ',,' and ',NA,' too (if they occurred in this column before the bump). If this matters please rerun and set 'colClasses' to 'character' for this column. Please note that column type detection uses a sample of 1,000 rows (100 rows at 10 points) so hopefully this message should be very rare. If reporting to datatable-help, please rerun and include the output from verbose=TRUE.
```

Best regards,
Niklas

**Comment by nunofonseca** [comment] 2017-09-07 09:10
Hi,
Thanks for the log files. Yes, you can ignore the warning.
Could you please run the following command and  and send the tsvDE2html.Rdata file generated? Note that the Rdata file will include the data given to the script - feel free to send it to me privately by email if you don't want to share here.

tsvDE2html --flavour voom --tsv Master2/tophat2/htseq1/voom/G0SvsGH2O2.genes_de.tsv --out Master2/report/tophat2/htseq1/voom/G0SvsGH2O2.genes_de --cut-off 0.05 --species homo_sapiens --feature gene --browser ../../../jbrowse/ --css ../../../irap.css --title "tophat2 x htseq1 x voom x G0SvsGH2O2" -a Master2/data/Homo_sapiens.GRCh38.dna.chromosome.1.fa.gene.annot.tsv -m 300 --debug

Cheers

**Comment by Niklas123Niklas** [comment] 2017-09-07 11:37
Hi,
I will sent it to you in the next days, because I started the analysis completely new. Thank you for the fast response. 
Best regards

**Comment by Niklas123Niklas** [comment] 2017-09-09 12:08
Hi,
I ran the command, but the --out directiory is empty. If the .Rdata file is elsewhere, can you tell me the name please?
And the log comes too:
[Debuglog.txt](https://github.com/nunofonseca/irap/files/1289765/Debuglog.txt)
Best regards

**Comment by Niklas123Niklas** [comment] 2017-09-09 12:15
I found a .Rdata file in the directory /Master2/tophat2/htseq1/voom/G0SvsGH2O2.genes_de.Rdata.

This one is attached here:
[G0SvsGH2O2.genes_de.Rdata.gz](https://github.com/nunofonseca/irap/files/1289773/G0SvsGH2O2.genes_de.Rdata.gz)

**Comment by nunofonseca** [comment] 2017-09-11 08:18
Hi,
Thank you for the log and Rdata file - this file was generated when running voom and is not the one that I'm looking for. You should see a tsvDE2html*.Rdata file in the folder where you ran the tsvDE2html command. 
Thanks.

**Comment by Niklas123Niklas** [comment] 2017-09-11 09:15
Hi,
there are two files, you get them booth. 
[Rdata.zip](https://github.com/nunofonseca/irap/files/1291992/Rdata.zip)
Best regards.

**Comment by nunofonseca** [comment] 2017-09-11 09:42
Hi, thanks for the Rdata files, they were quite useful.
I think that the problem is now fixed - could you please try replacing the file 
$IRAP_DIR/scripts/tsvDE2html  by https://github.com/nunofonseca/irap/blob/devel/scripts/tsvDE2html?

The following commands should do the work
cd $IRAP_DIR/scripts
wget https://raw.githubusercontent.com/nunofonseca/irap/devel/scripts/tsvDE2html
chmod +x tsvDE2html

Thanks.

**Comment by Niklas123Niklas** [comment] 2017-09-11 11:27
Hi,
this solved this issue. Later there occured a new one. It seems like there are some max/min values not defined? If you have problems with german messages I can translate it for you.

[log2.txt](https://github.com/nunofonseca/irap/files/1292344/log2.txt)

**Comment by nunofonseca** [comment] 2017-09-11 13:34
Hi,
I think that the warnings that you observe derive from the fact that the (log)fold change for several (sometimes all) genes is NA hence max/min values cannot be defined (and the plot may not be generated).  
Cheers.

**Comment by Niklas123Niklas** [comment] 2017-10-17 13:42
Thanks, this can be closed so far.

**Closed** 2017-10-18 11:06 UTC
